baseURL = "https://phuongit1306.github.io/BlogLTMMT/"
languageCode = "vi"
title = "Blog Láº­p TrÃ¬nh - 2180607911 - Nguyá»…n Thanh PhÆ°Æ¡ng - 21DTHD3"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  author = "Nguyá»…n Thanh PhÆ°Æ¡ng"
  description = "Chia sáº» kiáº¿n thá»©c, kinh nghiá»‡m vÃ  dá»± Ã¡n vá» Java, JavaScript, vÃ  láº­p trÃ¬nh máº¡ng."
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

  [params.assets]
    css = ["css/custom.css"]

  [params.profileMode]
    enabled = true
    title = "Nguyá»…n Thanh PhÆ°Æ¡ng ğŸ‘¨â€ğŸ’»"
    subtitle = """
    Láº­p trÃ¬nh viÃªn yÃªu thÃ­ch cÃ´ng nghá»‡ Java & Web.  
    ÄÃ¢y lÃ  nÆ¡i tÃ´i chia sáº» cÃ¡c kiáº¿n thá»©c, hÆ°á»›ng dáº«n, vÃ  kinh nghiá»‡m thá»±c chiáº¿n trong quÃ¡ trÃ¬nh há»c vÃ  lÃ m dá»± Ã¡n.  
    """
    imageUrl = "images/avatar.jpg"
    imageTitle = "Nguyá»…n Thanh PhÆ°Æ¡ng"
    buttons = [
      { name = "ğŸ“ Blog", url = "blog/" },
      { name = "ğŸ“© LiÃªn há»‡", url = "about/" },
      { name = "ğŸ“‚ GitHub", url = "https://github.com/phuongit1306" }
    ]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "ğŸ“"
  url = "/blog"
  weight = 2

[[menu.main]]
  name = "ğŸ“©"
  url = "/about"
  weight = 3
  
[[menu.main]]
  name = "ğŸ“"
  url = "/certificates"
  weight = 4